"""create_book_data_table

Revision ID: 203f86093b3b
Revises: 
Create Date: 2024-10-13 11:33:43.189053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203f86093b3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_data',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True, autoincrement=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(length=50000), nullable=True),
    sa.Column('authors', sa.String(length=5000), nullable=True),
    sa.Column('previewlink', sa.String(length=2000), nullable=True),
    sa.Column('infolink', sa.String(length=2000), nullable=True),
    sa.Column('categories', sa.String(length=2000), nullable=True),
    )
    op.create_index('ix_fulltext_title', 'book_data', ['title'], unique=False, mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fulltext_title', table_name='book_data', mysql_prefix='FULLTEXT')
    op.drop_table('book_data')
    # ### end Alembic commands ###
