"""add_unique_constraints

Revision ID: 5e955daf0d29
Revises: b64c1d3f2e96
Create Date: 2025-06-05 10:33:17.514725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e955daf0d29'
down_revision: Union[str, None] = 'b64c1d3f2e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_book_id_author_id', 'book_authors', ['book_id', 'author_id'])
    op.create_unique_constraint('category_id_book_id', 'book_categories', ['category_id', 'book_id'])
    op.create_unique_constraint('unique_category_id_user_id', 'liked_categories', ['category_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_category_id_user_id', 'liked_categories', type_='unique')
    op.drop_constraint('category_id_book_id', 'book_categories', type_='unique')
    op.drop_constraint('unique_book_id_author_id', 'book_authors', type_='unique')
    # ### end Alembic commands ###
