"""create_book_data_table

Revision ID: 6bf2e9b15bde
Revises: 
Create Date: 2024-10-12 20:40:24.829311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf2e9b15bde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.String(length=50000), nullable=True),
    sa.Column('authors', sa.String(length=5000), nullable=True),
    sa.Column('previewlink', sa.String(length=2000), nullable=True),
    sa.Column('infolink', sa.String(length=2000), nullable=True),
    sa.Column('categories', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_data')
    # ### end Alembic commands ###
