"""create_tables

Revision ID: afa90328bf9b
Revises: 
Create Date: 2024-10-26 14:29:56.273850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa90328bf9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('no_stop_word',
    sa.Column('value', sa.String(length=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('value')
    )

    #use this connection because execute returns value while op.execute doesn't
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT DATABASE();"))
    db_name = result.fetchone()[0]
    #create fts text search without stop words(stop words are words that are ignored)
    op.execute(f"SET GLOBAL innodb_ft_server_stopword_table = '{db_name}/no_stop_word';")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(length=50000), nullable=False),
    sa.Column('link', sa.String(length=2000), nullable=False),
    sa.Column('image_link', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fulltext_title', 'book', ['title'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('book_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_categories')
    op.drop_table('book_authors')
    op.drop_table('user')
    op.drop_table('no_stop_word')
    op.drop_index('ix_fulltext_title', table_name='book', mysql_prefix='FULLTEXT')
    op.drop_table('book')
    # ### end Alembic commands ###
